spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  session:
    store-type: none  #如果要使用redis的话就用redis     
  thymeleaf:
    prefix: classpath:/templates/   #设置访问的html
    suffix: .html
  resources:
    static-locations:
    - classpath:/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout:
      10000
    password: 
    jedis:
      pool:
        max-active: 60
        min-idle: 1000
        max-idle: 30
        max-wait: 10000
      
  mvc:
    static-path-pattern: /**
# mvc 只针对 jsp页面     
#  mvc:
#    view:
#      prefix: /views/
#      suffix: .jsp
  datasource: 
    url: jdbc:mysql://localhost:3306/wx?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8 
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
  
#spring.servlet.multipart.max-file-size: 50MB
#spring.servlet.multipart.max-file-size: 10MB
mybatis:
  config-location: classpath:SqlMapConfig.xml
#  这个不加可以成功是因为mapper和接口放在同一个包里，这里配置的是映射路径，
#如果两个不在同一个包里，那就要配置 ，最好都配置一次
  mapper-locations:
  - com.example.demo.mapper/*.xml
#  mapper-locations: com.example.demo.dao/*.xml
#  mapper-locations: 
#  - classpath:com.example.demo.dao/*Mapper.xml
  type-aliases-package: com.example.demo.entity
 
 
 


## Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=localhost
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=0


#.mvc.view.prefix=/views/
#spring.mvc.view.suffix=.jsp
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc\:mysql\://127.0.0.1\:3306/xiangmu?useUnicode\=true&characterEncoding\=utf8
#spring.datasource.username=root
#spring.datasource.password=123456
##tomcat \u7AEF\u53E3
#server.port=8080 
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jackson.serialization.indent-output=true
#mybatis.config-location=classpath:mybatis-config.xml 
#mybatis.mapper-locations=classpath*:conf/*Mapper.xml
#mybatis.type-aliases-package=com.example.demo.entity

